### ISSUE TITLE
Possibly inverted P-MOSFET on Power switch stage ?

### ISSUE THREAD

**Issue by martinroger** [martinroger/VXDash#33]
Hey @Alex-XNR , I was checking some things after dusting off the project a bit, and I noticed - just now - that actually the benchboard starts itself regardless of the ignition signal value. I dug up the schematic, and I think I found what is wrong but I might need to double check with you : 

![image](https://github.com/user-attachments/assets/8a7a6163-8285-4161-895a-71e31382727d)

On there, shouldn't Q2 have D and S reversed ? And R65 and D10 should connect to Power_Fused on the left side ? When I simulate it, it seems to work but I thought I would double check with you before correcting that !

**Comment by martinroger** [comment]
Candidate correction in 9ae1b542eb9109c802848487aa74be222306fe4f

**Comment by Alex-XNR** [comment]
Hi @martinroger, yes looks like an error 🫣 As you've said, flip drain and source, keep D10 + R65 between G-S.

**Comment by martinroger** [comment]
@Alex-XNR Imagine my face when I finally wondered why it was starting without me setting the ignition pin on...

![image](https://github.com/user-attachments/assets/31014b0b-9ecf-4316-8966-66cf03ef7989)

Some like this looks OK to you ?

**Comment by martinroger** [comment]
Closed by #35
